# name: Populate Select Options

# inputs:
#   json_file: required

# outputs:
#   options: string

# runs-on: ubuntu-latest

# steps:
#   - name: Read JSON File
#     run: |
#       # options=$(jq -r '.key1[] | @csv' ${{ inputs.json_file }})
#       echo "::set-output name=options::abc,pqr"

name: "Hello World"
description: "Greet someone"
inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  RANDOM_NUMBER:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    # - name: Set Greeting
    #   run: echo "Hello $INPUT_WHO_TO_GREET."
    #   shell: bash
    #   env:
    #     INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}

    # - name: Random Number Generator
    #   id: random-number-generator
    #   run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
    #   shell: bash

    # - name: Set GitHub Path
    #   run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
    #   shell: bash
    #   env:
    #     GITHUB_ACTION_PATH: ${{ github.action_path }}

    # - name: Run goodbye.sh
    #   run: goodbye.sh
    #   shell: bash

    - name: Read JSON File
      id: random-number-generator
      shell: bash
      run: echo "::set-output name=options::abc,pqr"
      # options=$(jq -r '.key1[] | @csv' ${{ inputs.json_file }})
      # echo "::set-output name=options::abc,pqr"
