name: Deploy Services
on:
  # push: {}
  workflow_dispatch:  
    inputs:
      name:
        type: choice
        description: Please choose the service to depoy - 
        default: 'NA'
        options: 
        - --SELECT SERVICE--
        - monalisa
        - cschleiden
        # required: true
      disclaimer:
        type: boolean
        description: I understand this will deploy my cloud service.
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        name: Checkout
      # - name: Populate Select Options
        # id: foo
        # uses: ./.github/actions/get-options
        # uses: action.yml
      - run: |
          echo "${{ github.event.inputs.name }}"
        shell: bash

