name: Populate Select Box

on:
  workflow_dispatch:  

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          token: ${{ secrets.MY_ACCESS_TOKEN }}

      # - name: Run a one-line script
      #   run: echo "Hello World" >> hello.txt
      # - name: switching from HTTPS to SSH
      #   run: git remote set-url origin ${{ secrets.ssh }}
      # - name: check for changes
      #   run: git status
      # - name: stage changed files
      #   run: git add .
      # - name: commit changed files
      #   run: git commit -m "Auto updating hello.txt"
      # - name: fetch from main
      #   run: git fetch origin main
      - name: push code to main
        # run: git push origin HEAD:main
        run: |
          # echo "Hello World" >> hello.txt
          # echo "Test push commit to the remote in the workflow" >> test.txt

          cat <<EOT > ./.github/workflows/deploy-services.yml
          name: Deploy Services
          on:
            # push: {}
            workflow_dispatch:  
              
          jobs:
            build:
              runs-on: ubuntu-latest
              steps:
                - uses: actions/checkout@main
                  name: Checkout
                - name: Populate Select Options
                  id: foo
                  uses: ./.github/actions/get-options
                  # uses: action.yml
                - run: |
                    echo "${{ steps.foo.outputs.options }}"
                  shell: bash

          EOT

          git config --global user.name "akhilmordia"
          git config --global user.email "akhil.mordia@gmail.com"
          git add -A
          git commit -m "Update hello.txt"
          git push
