name: Populate Select Box

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        name: Checkout
      - name: Populate Select Options
        id: foo
        uses: ./.github/actions/get-options
        # uses: action.yml
      - run: echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.options }}
