name: Populate Select Box

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        name: Checkout
      - name: Populate Select Options
        id: foo
        uses: ./.github/actions/get-options
        # uses: action.yml
      - run: |
          echo "${{ steps.foo.outputs.options }}"
        shell: bash
        