name: Populate Select Box

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Populate Select Options
        id: foo
        uses: .github/actions/get-options
        # uses: ./.github/actions/deploy-frontend-to-s3
      - run: echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.options }}
